version: '3'

services:

  mongodb:
    image: library/mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    ports:
      - ${MONGODB_HOST_PORT}:${MONGODB_CONTAINER_PORT}

  app:
    build: spring-docker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGODB_CONTAINER_NAME=$MONGODB_CONTAINER_NAME
      - MONGODB_CONTAINER_PORT=$MONGODB_CONTAINER_PORT
      - TWITTER_SEARCH_CONSUMER_KEY=$TWITTER_SEARCH_CONSUMER_KEY
      - TWITTER_SEARCH_CONSUMER_SECRET=$TWITTER_SEARCH_CONSUMER_SECRET
      - TWITTER_SEARCH_ACCESS_TOKEN=$TWITTER_SEARCH_ACCESS_TOKEN
      - TWITTER_SEARCH_ACCESS_TOKEN_SECRET=$TWITTER_SEARCH_ACCESS_TOKEN_SECRET
    ports:
      - ${SPRING_HOST_PORT}:${SPRING_CONTAINER_PORT}
    depends_on:
      - mongodb