version: '3'

services:

  mongodb:
    image: library/mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=lab5soa
    ports:
    - 27017:27017

  app:
    build: spring-docker
    ports:
    - 8080:8080
    depends_on:
      - mongodb